name: andhealthchat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider:
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  firebase_storage: ^12.3.2 
  file_picker: ^8.1.2
  path_provider: ^2.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
